//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/Imitation Modeliers/2P1/Scripts/InputMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Imitation Modeliers/2P1/Scripts/InputMap.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @InputMap: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @InputMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMap"",
    ""maps"": [
        {
            ""name"": ""JetEngine"",
            ""id"": ""0b3f0025-fa1d-40d1-97f6-72ede6838c3c"",
            ""actions"": [
                {
                    ""name"": ""throttlerUpHolder"",
                    ""type"": ""Button"",
                    ""id"": ""5d970ffa-06de-4123-a63a-5f361df62d32"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""throttlerDownHold"",
                    ""type"": ""Button"",
                    ""id"": ""f2427a12-a181-4ab7-a2d3-023ddc2ed983"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""throttleStepUp"",
                    ""type"": ""Button"",
                    ""id"": ""2886d3e7-3226-4cae-b418-3f0b6bc2772c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""throttleStepDown"",
                    ""type"": ""Button"",
                    ""id"": ""6ce612f0-d165-4b70-9503-142b1da7f3b3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""tooggleAB"",
                    ""type"": ""Button"",
                    ""id"": ""2e324c96-e7a5-4bc9-badc-b909a50323ab"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4bd7053b-43fc-4833-92b0-0275d0c5418e"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""throttlerUpHolder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""316ef90f-d993-4324-9349-ea52b0e55f08"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""throttlerDownHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60c5a643-6096-43d6-9de9-926b070171db"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""throttleStepUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19909f76-1123-45fc-835f-1b7663606d7a"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""throttleStepDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""835984f5-077b-4996-b44e-f88acd83e4a3"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""tooggleAB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // JetEngine
        m_JetEngine = asset.FindActionMap("JetEngine", throwIfNotFound: true);
        m_JetEngine_throttlerUpHolder = m_JetEngine.FindAction("throttlerUpHolder", throwIfNotFound: true);
        m_JetEngine_throttlerDownHold = m_JetEngine.FindAction("throttlerDownHold", throwIfNotFound: true);
        m_JetEngine_throttleStepUp = m_JetEngine.FindAction("throttleStepUp", throwIfNotFound: true);
        m_JetEngine_throttleStepDown = m_JetEngine.FindAction("throttleStepDown", throwIfNotFound: true);
        m_JetEngine_tooggleAB = m_JetEngine.FindAction("tooggleAB", throwIfNotFound: true);
    }

    ~@InputMap()
    {
        UnityEngine.Debug.Assert(!m_JetEngine.enabled, "This will cause a leak and performance issues, InputMap.JetEngine.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // JetEngine
    private readonly InputActionMap m_JetEngine;
    private List<IJetEngineActions> m_JetEngineActionsCallbackInterfaces = new List<IJetEngineActions>();
    private readonly InputAction m_JetEngine_throttlerUpHolder;
    private readonly InputAction m_JetEngine_throttlerDownHold;
    private readonly InputAction m_JetEngine_throttleStepUp;
    private readonly InputAction m_JetEngine_throttleStepDown;
    private readonly InputAction m_JetEngine_tooggleAB;
    /// <summary>
    /// Provides access to input actions defined in input action map "JetEngine".
    /// </summary>
    public struct JetEngineActions
    {
        private @InputMap m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public JetEngineActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "JetEngine/throttlerUpHolder".
        /// </summary>
        public InputAction @throttlerUpHolder => m_Wrapper.m_JetEngine_throttlerUpHolder;
        /// <summary>
        /// Provides access to the underlying input action "JetEngine/throttlerDownHold".
        /// </summary>
        public InputAction @throttlerDownHold => m_Wrapper.m_JetEngine_throttlerDownHold;
        /// <summary>
        /// Provides access to the underlying input action "JetEngine/throttleStepUp".
        /// </summary>
        public InputAction @throttleStepUp => m_Wrapper.m_JetEngine_throttleStepUp;
        /// <summary>
        /// Provides access to the underlying input action "JetEngine/throttleStepDown".
        /// </summary>
        public InputAction @throttleStepDown => m_Wrapper.m_JetEngine_throttleStepDown;
        /// <summary>
        /// Provides access to the underlying input action "JetEngine/tooggleAB".
        /// </summary>
        public InputAction @tooggleAB => m_Wrapper.m_JetEngine_tooggleAB;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_JetEngine; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="JetEngineActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(JetEngineActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="JetEngineActions" />
        public void AddCallbacks(IJetEngineActions instance)
        {
            if (instance == null || m_Wrapper.m_JetEngineActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_JetEngineActionsCallbackInterfaces.Add(instance);
            @throttlerUpHolder.started += instance.OnThrottlerUpHolder;
            @throttlerUpHolder.performed += instance.OnThrottlerUpHolder;
            @throttlerUpHolder.canceled += instance.OnThrottlerUpHolder;
            @throttlerDownHold.started += instance.OnThrottlerDownHold;
            @throttlerDownHold.performed += instance.OnThrottlerDownHold;
            @throttlerDownHold.canceled += instance.OnThrottlerDownHold;
            @throttleStepUp.started += instance.OnThrottleStepUp;
            @throttleStepUp.performed += instance.OnThrottleStepUp;
            @throttleStepUp.canceled += instance.OnThrottleStepUp;
            @throttleStepDown.started += instance.OnThrottleStepDown;
            @throttleStepDown.performed += instance.OnThrottleStepDown;
            @throttleStepDown.canceled += instance.OnThrottleStepDown;
            @tooggleAB.started += instance.OnTooggleAB;
            @tooggleAB.performed += instance.OnTooggleAB;
            @tooggleAB.canceled += instance.OnTooggleAB;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="JetEngineActions" />
        private void UnregisterCallbacks(IJetEngineActions instance)
        {
            @throttlerUpHolder.started -= instance.OnThrottlerUpHolder;
            @throttlerUpHolder.performed -= instance.OnThrottlerUpHolder;
            @throttlerUpHolder.canceled -= instance.OnThrottlerUpHolder;
            @throttlerDownHold.started -= instance.OnThrottlerDownHold;
            @throttlerDownHold.performed -= instance.OnThrottlerDownHold;
            @throttlerDownHold.canceled -= instance.OnThrottlerDownHold;
            @throttleStepUp.started -= instance.OnThrottleStepUp;
            @throttleStepUp.performed -= instance.OnThrottleStepUp;
            @throttleStepUp.canceled -= instance.OnThrottleStepUp;
            @throttleStepDown.started -= instance.OnThrottleStepDown;
            @throttleStepDown.performed -= instance.OnThrottleStepDown;
            @throttleStepDown.canceled -= instance.OnThrottleStepDown;
            @tooggleAB.started -= instance.OnTooggleAB;
            @tooggleAB.performed -= instance.OnTooggleAB;
            @tooggleAB.canceled -= instance.OnTooggleAB;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="JetEngineActions.UnregisterCallbacks(IJetEngineActions)" />.
        /// </summary>
        /// <seealso cref="JetEngineActions.UnregisterCallbacks(IJetEngineActions)" />
        public void RemoveCallbacks(IJetEngineActions instance)
        {
            if (m_Wrapper.m_JetEngineActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="JetEngineActions.AddCallbacks(IJetEngineActions)" />
        /// <seealso cref="JetEngineActions.RemoveCallbacks(IJetEngineActions)" />
        /// <seealso cref="JetEngineActions.UnregisterCallbacks(IJetEngineActions)" />
        public void SetCallbacks(IJetEngineActions instance)
        {
            foreach (var item in m_Wrapper.m_JetEngineActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_JetEngineActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="JetEngineActions" /> instance referencing this action map.
    /// </summary>
    public JetEngineActions @JetEngine => new JetEngineActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "JetEngine" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="JetEngineActions.AddCallbacks(IJetEngineActions)" />
    /// <seealso cref="JetEngineActions.RemoveCallbacks(IJetEngineActions)" />
    public interface IJetEngineActions
    {
        /// <summary>
        /// Method invoked when associated input action "throttlerUpHolder" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThrottlerUpHolder(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "throttlerDownHold" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThrottlerDownHold(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "throttleStepUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThrottleStepUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "throttleStepDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThrottleStepDown(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "tooggleAB" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTooggleAB(InputAction.CallbackContext context);
    }
}
